name: 'Configuration Environment'
type: module
description: 'Allows administrators to manage configuration environments.'
package: Core (Experimental)
# version: VERSION
core: 8.x
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2020-03-02
version: '8.9.x-dev'
project: 'drupal'
datestamp: 1583152365
