name: Config Ignore
type: module
description: Ignore certain configuration during import
# core: 8.x
package: Config
configure: config_ignore.settings
dependencies:
  - config_filter

# Information added by Drupal.org packaging script on 2017-04-26
version: '8.x-2.0-rc2'
core: '8.x'
project: 'config_ignore'
datestamp: 1493232409
