name: OpenAPI
type: module
description: Connects Drupal to the OpenAPI Javascript Library
core: 8.x
package: OpenAPI
dependencies:
  - schemata:schemata
  - schemata:schemata_json_schema

# Information added by Drupal.org packaging script on 2020-04-01
version: '8.x-1.0-beta7'
project: 'openapi'
datestamp: 1585778032
