field.formatter.settings.bg_img_field_formatter:
  type: mapping
  label: 'Image URL formatter settings'
  mapping:
    image_style:
      type: string
      label: 'Image style'

field.widget.settings.bg_img_field_widget:
  type: mapping
  label: 'Default field settings'
  mapping:
    css_settings:
      type: mapping
      label: 'CSS settings'
      mapping:
        css_selector:
          type: string
          label: 'CSS selector to attach the background image to.'
        css_repeat:
          type: string
          label: 'CSS property to determine repeat value.'
        css_background_size:
          type: string
          label: 'CSS property to determine background size value.'
        css_background_position:
          type: string
          label: 'CSS property to determine background position value'