name: 'Configuration Inspector'
type: module
description: 'Provides a configuration data and structure inspector tool.'
package: Development
configure: config_inspector.overview
core_version_requirement: ^8 || ^9
core: 8.x
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2019-09-25
version: '8.x-1.0'
project: 'config_inspector'
datestamp: 1569419589
